- beginnings of kernel log attempt - correct some badblocks behavior

diff --git a/bin/disktest b/bin/disktest
--- a/bin/disktest
+++ b/bin/disktest
@@ -12,7 +12,7 @@ class HardDrive
   UNTESTED = 2
 
   def HardDrive.scan
-    # load the modules
+    # :TODO: check for and load the modules?
     Dir.open('/sys/block').find_all {|dev|
       /^[sh]d[a-z]/.match(dev) and
       `cat /sys/block/#{dev}/removable`.chomp == '0'
@@ -49,8 +49,8 @@ class HardDrive
   def smart
     log << "smart test started"
     if ! system('/usr/sbin/smartctl', '-q', 'silent', '--all', dev)
+      log << "smart test returned: '#{$?.exitstatus}'"
       if $?.exitstatus > 4
-        log << "smart test returned: '#{$?.exitstatus}'"
         @status = FAILED
         return false
       end
@@ -65,7 +65,9 @@ class HardDrive
     buff = ""
     # progress comes in through err, bad blocks are reported on out
     bbpid, bbin, bbout, bberr = Open4.popen4("#{File.dirname(__FILE__)}/fake_badblocks -c 1024 -s /dev/#{dev}")
-    # :TODO: test with "/sbin/badblocks -c 1024 -swt 0xffffffff /dev/#{dev}"
+    #bbpid, bbin, bbout, bberr = Open4.popen4("/sbin/badblocks -c 1024 -s /dev/#{dev}")
+    #bbpid, bbin, bbout, bberr = Open4.popen4("/sbin/badblocks -c 1024 -swt 0xffffffff /dev/#{dev}")
+    bbout.sync = bberr.sync = true
     until bberr.closed? or bberr.eof?
       reads, writes, errs = IO.select([bbout, bberr], nil, nil, 1)
       if reads
@@ -73,20 +75,18 @@ class HardDrive
         sectors = reads.include?(bbout) ? bbout : nil
       end
       done, total = nil
-      if sectors
-        buff << sectors.read(30)
-        # :TODO: find out what this regex should be
-        if /bad/.match(buff)
-          @status = FAILED
-          log << "bad sectors found"
-          [bbin, bbout, bberr].each {|io| io.close}
-          Process.kill("INT", bbpid)
-        end
+      if sectors and ! sectors.eof?
+        buff = sectors.read_nonblock(1000, buff)
+        # :TODO: find out what this means for sure
+        @status = FAILED
+        curr = log[-1]
+        log[-1] = "badblocks reports failures"
+        log << curr
         buff.replace("")
       end
       if progress and ! progress.closed?
         until( (done and total) or bberr.eof? )
-          buff << progress.read(100)
+          buff = progress.read_nonblock(1000, buff)
           done, total = buff.scan( %r,(\d+)\s*/\s*(\d+)[^\d]+, )[0]
         end
         if done and total and (total.to_i >= done.to_i)
@@ -94,12 +94,21 @@ class HardDrive
         end
         buff.replace("")
       end
+      if @status == FAILED
+        [bbin, bbout, bberr].each {|io| io.close}
+        Process.kill("INT", bbpid)
+        break
+      end
+    end
+    if Process::waitpid2(bbpid)[1].exitstatus.nonzero?
+      @log << "badblocks failed"
+      @status = FAILED
     end
     return @status != FAILED
-  end
+  end # def badblocks
 
   def wipe
-    log << "disk wipe started"
+    log << "disk wipe stub"
     return true
   end
 
@@ -123,10 +132,26 @@ class HardDrive
     @status == PASSED
   end
 
-  def klog_match(line)
-    /kernel: /.match(line) and
-      /error/.match(line) and
+  def failed?
+    @status == FAILED
+  end
+
+  Err_re = /error/
+  def klog_match?(line)
+    Err_re.match(line) and
       /#{@dev}/.match(line)
+  end
+
+  def klog(*msgs)
+    msgs.each do |msg|
+      if klog_match?(msg)
+        @status = FAILED
+        #:MC: ugly handling of continuously updating progress log entry
+        curr = log[-1]
+        log[-1] = msg
+        log << curr
+      end
+    end
   end
 
 end
@@ -134,27 +159,52 @@ end
 if __FILE__ == $0
   require 'optparse'
   trap( "SIGINT" ) do
-    #`reset -Q`
     errorMessage "\n\nUser interrupt caught.  Exiting.\n\n"
     exit!( 1 )
   end
-  # check that i'm root
-  # alter the syslogs
-  drives = HardDrive.scan
-  threads = drives.map {|drive| drive.run_tests}
-  until threads.empty?
-    `clear`
-    drives.each {|d| d.output_display}
-    threads = threads.find_all {|t|
-      t.alive? 
+  begin
+    # :TODO: check that i'm root
+    logpipe = "/tmp/klog"
+    logconf = "/tmp/syslog.conf"
+    `mkfifo #{logpipe}`
+    open(logconf, 'w') {|conf|
+      conf.puts "*.* |#{logpipe}"
+      #conf.puts "*.* /dev/console"
     }
-    sleep 2
-  end
-  header "Final status:"
-  drives.each {|d| 
-    d.output_display
-    if d.passed?
-      puts ansiCode( 'green', 'bold' ) + "#{d.dev} passed!" + ansiCode( 'reset' )
+    `/usr/sbin/invoke-rc.d sysklogd stop`
+    `/sbin/syslogd -f #{logconf}`
+    klpid, klin, klout, klerr = open4("tail -F #{logpipe}")
+    loglines = []
+    drives = HardDrive.scan
+    threads = drives.map {|drive| drive.run_tests}
+    clearer = `clear`
+    until threads.empty?
+      if select([klout],nil,nil,0.1)
+        loglines += klout.read_nonblock(1000).split("\n")
+      end
+      drives.each {|d|
+        d.klog(*(loglines.delete_if {|l| d.klog_match?(l)}))
+        d.output_display
+      }
+      loglines.clear
+      threads = threads.find_all {|t|
+        t.alive? 
+      }
+      sleep 1
+      $stderr.write(clearer)
+      $stderr.flush
     end
-  }
+  ensure
+    header "Final status:"
+    drives.each {|d| 
+      d.output_display
+      if d.passed?
+        puts colored( "#{d.dev} passed!  Label and store it.", 'green', 'bold' )
+      elsif d.failed?
+        errorMessage "#{d.dev} failed.  Recycle it.\n"
+      else
+        errorMessage "#{d.dev} did not finish testing.  Seek expert attention."
+      end
+    }
+  end
 end
