allow to override interactive prompting

diff --git a/bin/lessdisks-cloner b/bin/lessdisks-cloner
--- a/bin/lessdisks-cloner
+++ b/bin/lessdisks-cloner
@@ -108,6 +108,8 @@ else
   echo "using default values from /etc/lessdisks/cloner.config" 
 fi
 
+test -z "$INTERACTIVE" && INTERACTIVE=true
+
 getDisks () {
   dmesg | egrep CHS | egrep ^hd | cut -d : -f 1 | sort -u
 }
@@ -129,28 +131,30 @@ PartitionDisks () {
 
   continue="no"
   while [ "no" = "$continue" ]; do
-    clear
-    echo "This program is distributed in the hope that it will be"
-    echo "useful, but WITHOUT ANY WARRANTY; without even the"
-    echo "implied warranty of MERCHANTABILITY or FITNESS FOR A"
-    echo "PARTICULAR PURPOSE. See the"
-    echo "GNU General Public License (version 2, or any later version)"
-    echo "for more details."
-    echo
-    echo "NOTE: partitioning disks may destroy any and all"
-    echo "data, files, Operating Systems, and other information"
-    echo "on this computer. BACK UP any important data on"
-    echo 'the computer before proceeding!'
-    echo
-    echo "attempt to automatically partition disks? (Y/n/quit)"
-    echo
-    read autopartition
-    case $autopartition in
-      n|no|N) fstab_interactive="yes" ;;
-      q|quit|exit) echo "exiting..."
-        exit 1 ;;
-      *) echo "full-on autopartitioning commencing..." ;;
-    esac
+    if boolean_is_true "$INTERACTIVE" ; then
+      clear
+      echo "This program is distributed in the hope that it will be"
+      echo "useful, but WITHOUT ANY WARRANTY; without even the"
+      echo "implied warranty of MERCHANTABILITY or FITNESS FOR A"
+      echo "PARTICULAR PURPOSE. See the"
+      echo "GNU General Public License (version 2, or any later version)"
+      echo "for more details."
+      echo
+      echo "NOTE: partitioning disks may destroy any and all"
+      echo "data, files, Operating Systems, and other information"
+      echo "on this computer. BACK UP any important data on"
+      echo 'the computer before proceeding!'
+      echo
+      echo "attempt to automatically partition disks? (Y/n/quit)"
+      echo
+      read autopartition
+      case $autopartition in
+        n|no|N) fstab_interactive="yes" ;;
+        q|quit|exit) echo "exiting..."
+          exit 1 ;;
+        *) echo "full-on autopartitioning commencing..." ;;
+      esac
+    fi
 
     # test for existence of a schemefile, a model-specific scheme file, or the default scheme file
     for diskscheme in $schemefile $clonepath/$model/etc/lessdisks-cloner/diskschemes /etc/lessdisks/diskschemes ; do
@@ -178,38 +182,40 @@ PartitionDisks () {
       sfdisk -f /dev/$device < /tmp/$device
     done
 
-    clear
-    # TODO only display lines which report a size
-    echo "the following is the partitioning scheme required for this configuration:"
-    echo ""
-
-    awk '/#size=/{print $1" "$7}' $fstab | awk -F "#size=" '{print $1" "$2}' | sort
-    echo ""
-
-    echo "this is what the partitioned disks actually look like:"
-
-    for device in $disks; do
-      sfdisk -l -uM /dev/$device | sed s/\*//g | awk '/^\/dev/{print $1" "$3}' | sed s/-//g | sort
-    done
-    echo ""
-
-    echo "there may be slight discrepencies(+/-25MB) in size."
-    echo "if it's a compaq there may be an extra partition (/dev/hda4)"
-    echo ""
-    echo "Do they look similar enough? (Y/n/q/m)"
-    echo "yes is default(hit enter to accept), other options: no, quit, manual"
-    read partitionsok
-    case $partitionsok in
-      Y|Yes|yes|y|"") continue="yes"
-        echo "continuing with installation..." ;;
-      exit|q|quit) echo "exiting at your request..."
-        exit 1 ;;
-      manual|m) echo "will someday support cfdisk and/or fstab editing manually, but not today."
-      ;;
-      *) continue="no"
-        echo "partitioning failed? setting partitioning to interactive mode..."
-        fstab_interactive="yes" ;;
-    esac
+    if boolean_is_true "$INTERACTIVE" ; then
+      clear
+      # TODO only display lines which report a size
+      echo "the following is the partitioning scheme required for this configuration:"
+      echo ""
+  
+      awk '/#size=/{print $1" "$7}' $fstab | awk -F "#size=" '{print $1" "$2}' | sort
+      echo ""
+  
+      echo "this is what the partitioned disks actually look like:"
+  
+      for device in $disks; do
+        sfdisk -l -uM /dev/$device | sed s/\*//g | awk '/^\/dev/{print $1" "$3}' | sed s/-//g | sort
+      done
+      echo ""
+  
+      echo "there may be slight discrepencies(+/-25MB) in size."
+      echo "if it's a compaq there may be an extra partition (/dev/hda4)"
+      echo ""
+      echo "Do they look similar enough? (Y/n/q/m)"
+      echo "yes is default(hit enter to accept), other options: no, quit, manual"
+      read partitionsok
+      case $partitionsok in
+        Y|Yes|yes|y|"") continue="yes"
+          echo "continuing with installation..." ;;
+        exit|q|quit) echo "exiting at your request..."
+          exit 1 ;;
+        manual|m) echo "will someday support cfdisk and/or fstab editing manually, but not today."
+        ;;
+        *) continue="no"
+          echo "partitioning failed? setting partitioning to interactive mode..."
+          fstab_interactive="yes" ;;
+      esac
+    fi
   done
 }
 
